INSERT INTO FACTURA (CODIGO,IMPORTE,TIPO) VALUES ('COD0001', 1000, 'SERVICIOS');
INSERT INTO FACTURA (CODIGO,IMPORTE,TIPO) VALUES ('COD0002', 500, 'CONSUMOS');
INSERT INTO FACTURA (CODIGO,IMPORTE,TIPO) VALUES ('COD0003', 2000, 'SERVICIOS');
INSERT INTO FACTURA (CODIGO,IMPORTE,TIPO) VALUES ('COD0004', 700, 'CONSUMOS');